spring.application.name=farma-api

# Configuracoes do servidor - AGORA LIBERADO PARA A REDE
server.port=8080
#server.address=0.0.0.0

# Configuracoes do PostgreSQL
# Certifique-se de que este IP (10.147.20.64) ou (192.168.15.201) esta acessivel pelo servidor da API
spring.datasource.url=jdbc:postgresql://192.168.15.201:5432/sgfpod1
spring.datasource.username=consulta
spring.datasource.password=consultoria123
spring.datasource.driver-class-name=org.postgresql.Driver