spring.application.name=farma-api

# Configuracoes do servidor - AGORA LIBERADO PARA A REDE
server.port=8080
#server.address=0.0.0.0

# Configuracoes do PostgreSQL
# Certifique-se de que este IP (10.147.20.64) ou (192.168.15.201) esta acessivel pelo servidor da API
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=
